version: "3.7"

services:
  # This should become the built in "404 / maintainence page"
  # need a way to tell cirri-infra not to instanciate this, because we have one...
  maintainence:
    image: jwilder/whoami
    networks:
      - cirri_proxy
    labels:
      virtual.port: 8000
  hello:
    image: jwilder/whoami
    networks:
      - cirri_proxy
    labels:
      virtual.port: 8000
      virtual.host: host
  sub:
    image: jwilder/whoami
    networks:
      - cirri_proxy
    labels:
      virtual.port: 8000
      virtual.host: host
      virtual.path: /sub*

networks:
  cirri_proxy:
    name: cirri_proxy
    #driver: overlay
